- name: Create Backend Directory
  file:
    path: ~/backend
    state: directory

- copy:
    src: ~/project/.circleci/ansible/roles/deploy/artifact.tar.gz
    dest: ~/backend

- name: Extract artifact.tar.gz to EC2 
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    sudo apt-get install -y nodejs
    npm i
- name: Start the app
  shell: |
    export TYPEORM_ENTITIES=./backend/dist/modules/domain/**/*.entity{.ts,.js}
    export TYPEORM_HOST=localhost
    export TYPEORM_PORT=5532
    export TYPEORM_USERNAME=postgres
    export TYPEORM_PASSWORD=password
    export TYPEORM_DATABASE=glee
    export TYPEORM_MIGRATIONS_DIR=./backend/dist/migrations
    export TYPEORM_MIGRATIONS=./backend/dist/migrations/*.ts
    pm2 stop default
    pm2 start -f ~/backend/dist/main.js