- name: Create Backend Directory
  file:
    path: /home/ubuntu/backend
    state: directory

- copy:
    src: ~/project/.circleci/ansible/roles/deploy/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Extract artifact.tar.gz to EC2 
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

# - name: "Installing Node Dependencies"
#   shell: |
#     cd /home/ubuntu/backend
#     sudo apt update
#     sudo apt install npm -y
#     sudo npm install pm2 -g
#     npm i
- name: Start the app
  shell: |
    cd /home/ubuntu/backend
    echo NODE_ENV=production >> .env
    echo TYPEORM_CONNECTION=postgres >> .env
    echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> .env
    echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> .env
    echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> .env
    echo TYPEORM_HOST=$TYPEORM_HOST >> .env
    echo TYPEORM_PORT=$TYPEORM_PORT >> .env
    echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> .env
    echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> .env
    echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> .env
    npm install
    npm run build
    pm2 stop default
    pm2 start npm -- start