---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Extract backend
  unarchive:
    src: artifact.tar.gz
    dest: ~/web
- name: install npm & pm2
  shell: |
    sudo apt update
    sudo apt install npm -y
    npm install pm2 -g
    npm i


- name: Executing node
  shell: |
    cd ~/web/backend
    echo NODE_ENV=production >> .env
    echo TYPEORM_CONNECTION=postgres >> .env
    echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> .env
    echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> .env
    echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> .env
    echo TYPEORM_HOST=$TYPEORM_HOST >> .env
    echo TYPEORM_PORT=$TYPEORM_PORT >> .env
    echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> .env
    echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> .env
    echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> .env
    sudo apt update -y
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    sudo apt-get install -y nodejs    
    npm install pm2 -g
    npm install
    npm run build
    pm2 stop default
    pm2 start npm -- start
